### ISSUE TITLE
Browserify "breaks" after importing 'quill-mention' (CSS import fails)

### ISSUE THREAD

**Issue by AeonFr** [afry/quill-mention#86]
I'm importing assets in my code like this...

```
'use strict';

import React from 'react';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css'; // <-- A CSS Import
import QuillMention from 'quill-mention';
```

As you can see in the code sample, I'm importing a CSS file myself and I don't have any problem. Yet, when importing `quill-mention`, browserify throws an exception:

```
[07:59:26] Error: Parsing file C:\xampp\htdocs\ola\node_modules\quill-mention\src\quill.mention.js: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Deps.parseDeps (C:\xampp\htdocs\ola\node_modules\module-deps\index.js:510:15)
    at getDeps (C:\xampp\htdocs\ola\node_modules\module-deps\index.js:438:44)
    at C:\xampp\htdocs\ola\node_modules\module-deps\index.js:421:38
    at ConcatStream.<anonymous> (C:\xampp\htdocs\ola\node_modules\concat-stream\index.js:37:43)
    at ConcatStream.emit (events.js:194:15)
    at ConcatStream.EventEmitter.emit (domain.js:459:23)
    at finishMaybe (C:\xampp\htdocs\ola\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at endWritable (C:\xampp\htdocs\ola\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at ConcatStream.Writable.end (C:\xampp\htdocs\ola\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DuplexWrapper.onend (C:\xampp\htdocs\ola\node_modules\readable-stream\lib\_stream_readable.js:577:10)
```

The error seems to be in this line of `quill-mentions` I guess

This is my gulpfile (Note: I've tried things like changing the order of the browserify transforms, the `extensions` option of browserify, the `poll` option of browserify-css, and basically I've tried anything I saw online but nothing works):

``` js
const gulp = require("gulp"),
    browserify = require('browserify'),
    babelify = require('babelify'),
    browserifyCSS = require('browserify-css'),
    reactify = require('reactify');

gulp.task('jsx', () => {
    // set up the browserify instance on a task basis
    var b = browserify({
        entries: './Admin/js/src/comentarios.widget.jsx',
        // extensions: ['js', 'jsx', 'css'], // this doesn't seem to solve the issue
        debug: true,
        paths: ['./Admin/js/src/components/'],

        // The order in which the `browserifyCSS` transform is put doesn't seem to have any effect
        transform: [
            [babelify, { presets: ["env", "react"] }],
            [browserifyCSS, {
                minify: true,
                autoInyect: true,
            }],
            [reactify, { "es6": true }],
        ],
    });

    return b.bundle().pipe(gulp.dest('./Admin/js/dist/'));
});
```

I would appreciate if someone with a little more understanding of CSS imports could point me in the right direction.

**Comment by AeonFr** [comment]
Update:
I realized the library was using typescript, so I added the `tsify` plug-in to properly read the TypeScript code, but the error persists.

``` js
// before b.bundle().pipe(...
b.plugin(tsify, { compilerOptions: { lib: ["es2015", "es2016"] } });
```

``` json
// tsconfig.json
{
    "compilerOptions": {
        "lib": [
            "es2015",
            "es2016"
        ],
        "types": [
            // add node as an option
            "node"
        ],
        "typeRoots": [
            // add path to @types
            "node_modules/@types"
        ]
    },
    "exclude": [
        "vendor"
    ]
}
```

**Comment by MadSpindel** [comment]
Could you try if the new 2.2.1 version works better for you?
